{% set name = "aws-cdk.aws-kinesis" %}
{% set version = "1.204.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aws-cdk.aws-kinesis-{{ version }}.tar.gz
  sha256: 3cbb7ce4965b28daad154af4217a894ca73527ee6966c2b5b2710cc70d3c527b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=67.3.2,<67.4.dev0
    - wheel >=0.40,<1.dev0
    - pip
  run:
    - python >=3.7
    - aws-cdk.aws-cloudwatch ==1.204.0
    - aws-cdk.aws-iam ==1.204.0
    - aws-cdk.aws-kms ==1.204.0
    - aws-cdk.aws-logs ==1.204.0
    - aws-cdk.core ==1.204.0
    - constructs >=3.3.69,<4.0.0
    - python-jsii >=1.84.0,<2.0.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<2.14.dev0

test:
  imports:
    - aws_cdk.aws_kinesis
    - aws_cdk.aws_kinesis._jsii
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/aws-cdk
  summary: The CDK Construct Library for AWS::Kinesis
  dev_url: https://github.com/aws/aws-cdk.git
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
